<?php
/** @var \Application\Entities\Country $country */
/** @var \Application\Entities\City[] $cities */
?>

<p><a href="/"><< Countries</a></p>

<h1><?php echo $country->getName(); ?></h1>
<h3><?php echo $country->getContinent(); ?></h3>

<div class="row">
    <div class="col-lg-4">
        <h5>Population:</h5>
        <p><?php echo $country->getPopulation(); ?></p>

        <?= $country->getCode(); ?>
    </div>

    <div class="col-lg-4">
        <h5>Surface Area</h5>
        <p><?php echo $country->getSurfaceArea(); ?></p>
    </div>

    <div class="col-lg-4">
        <h5>Life Expectancy</h5>
        <p><?php echo $country->getLifeExpectancy(); ?></p>
    </div>
</div>

<h4>Cities</h4>

<ul>
    <?php foreach($cities as $city) {
        echo "<li><a href='/city/{$city->getID()}'>{$city->getName()}</a></li>";
} ?>

</ul>